### ISSUE TITLE
com.google.gson.JsonParseException: Type information is unavailable, and the target object is not a primitive

### ISSUE THREAD

**Issue by linch526** [PingPlusPlus/pingpp-java#15]
demo直接运行Main方法，一直报错，如下，第一次集成这个支付，好无力，求大神解答，
警告: Overriding the existing type handler for interface java.util.Map
Exception in thread "main" com.google.gson.JsonParseException: Type information is unavailable, and the target object is not a primitive: {"orderInfo":"_input_charset=\"utf-8\"&body=\"Your Body\"&it_b_pay=\"2016-06-03 16:31:15\"&notify_url=\"https%3A%2F%2Fapi.pingxx.com%2Fnotify%2Fcharges%2Fch_yHS0CC4qTerDmznHWLj5WHKC\"&out_trade_no=\"1464856241617rbrm4vv\"&partner=\"2008536698119845\"&payment_type=\"1\"&seller_id=\"2008536698119845\"&service=\"mobile.securitypay.pay\"&subject=\"Your Subject\"&total_fee=\"1.00\"&sign=\"UG1EdVBTTGF2TEdLNW1UaTUweWZmYnJQ\"&sign_type=\"RSA\""}
	at com.google.gson.JsonObjectDeserializationVisitor.visitPrimitive(JsonObjectDeserializationVisitor.java:130)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:116)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
	at com.google.gson.MapTypeAdapter.deserialize(MapTypeAdapter.java:68)
	at com.google.gson.MapTypeAdapter.deserialize(MapTypeAdapter.java:33)
Disconnected from the target VM, address: '127.0.0.1:58520', transport: 'socket'
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
	at com.google.gson.JsonObjectDeserializationVisitor.visitFieldUsingCustomHandler(JsonObjectDeserializationVisitor.java:117)
	at com.google.gson.ReflectingFieldNavigator.visitFieldsReflectively(ReflectingFieldNavigator.java:63)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:120)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:551)
	at com.google.gson.Gson.fromJson(Gson.java:521)
	at com.pingplusplus.net.ChargeDeserializer.deserialize(ChargeDeserializer.java:49)
	at com.pingplusplus.net.ChargeDeserializer.deserialize(ChargeDeserializer.java:20)
	at com.google.gson.JsonDeserializerExceptionWrapper.deserialize(JsonDeserializerExceptionWrapper.java:51)
	at com.google.gson.JsonDeserializationVisitor.invokeCustomDeserializer(JsonDeserializationVisitor.java:92)
	at com.google.gson.JsonDeserializationVisitor.visitUsingCustomHandler(JsonDeserializationVisitor.java:80)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:101)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:76)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:551)
	at com.google.gson.Gson.fromJson(Gson.java:498)
	at com.google.gson.Gson.fromJson(Gson.java:467)
	at com.google.gson.Gson.fromJson(Gson.java:417)
	at com.google.gson.Gson.fromJson(Gson.java:389)
	at com.pingplusplus.net.APIResource.request(APIResource.java:543)
	at com.pingplusplus.model.Charge.create(Charge.java:274)
	at com.pingxx.example.ChargeExample.createCharge(ChargeExample.java:71)
	at com.pingxx.example.ChargeExample.runDemos(ChargeExample.java:37)
	at com.pingxx.example.Main.main(Main.java:48)

**Comment by Ftamsir** [comment]
pom文件里更新一下gson的版本就好了

**Comment by czzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz** [comment]
我也遇到了此问题，请问下怎么解决的啊

**Comment by Ftamsir** [comment]
我这里用的gson是2.8.0版本的，应该是gson版本问题，我是更换了版本就好了



------------------ 原始邮件 ------------------
发件人: "czzz"<notifications@github.com>; 
发送时间: 2019年4月18日(星期四) 下午3:28
收件人: "PingPlusPlus/pingpp-java"<pingpp-java@noreply.github.com>; 
抄送: "294039391"<294039391@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [PingPlusPlus/pingpp-java] com.google.gson.JsonParseException:Type information is unavailable, and the target object is not a primitive(#15)




我也遇到了此问题，请问下怎么解决的啊

**Comment by czzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz** [comment]
好的，我刚才试着升级了版本，也成功了！非常感谢
